// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(potty_bridgeFFI)
import potty_bridgeFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_potty_bridge_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_potty_bridge_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Main client for the Potty Spotify bridge
 */
public protocol PottyClientProtocol : AnyObject {
    
    /**
     * Advanced search with filters and type selection
     *
     * # Arguments
     * * `query` - The base search query string
     * * `search_type` - Type of results to return (All, Track, Album, Artist)
     * * `artist_filter` - Optional artist name filter
     * * `album_filter` - Optional album name filter
     * * `track_filter` - Optional track name filter
     * * `limit` - Maximum number of results per type (max 50)
     * * `offset` - The offset for pagination (0-based)
     */
    func advancedSearch(query: String, searchType: PottySearchType, artistFilter: String?, albumFilter: String?, trackFilter: String?, limit: UInt32, offset: UInt32) throws  -> PottySearchResults
    
    /**
     * Gets the user's liked/saved songs with pagination support
     *
     * # Arguments
     * * `offset` - The offset for pagination (0-based)
     * * `limit` - Maximum number of results to return (max 50)
     */
    func getLikedSongs(offset: UInt32, limit: UInt32) throws  -> [PottyTrack]
    
    /**
     * Gets tracks from a specific playlist
     */
    func getPlaylistTracks(playlistId: String) throws  -> [PottyTrack]
    
    /**
     * Gets the user's followed artists
     */
    func getUserFollowedArtists() throws  -> [PottyArtist]
    
    /**
     * Gets the user's playlists
     */
    func getUserPlaylists() throws  -> [PottyPlaylist]
    
    /**
     * Gets the user's saved albums with pagination support
     *
     * # Arguments
     * * `offset` - The offset for pagination (0-based)
     * * `limit` - Maximum number of results to return (max 50)
     */
    func getUserSavedAlbums(offset: UInt32, limit: UInt32) throws  -> [PottyAlbum]
    
    /**
     * Gets the current playback volume (0-65535, where 65535 is 100%)
     */
    func getVolume() throws  -> UInt16
    
    /**
     * Authenticates with Spotify and initializes the session
     */
    func login() throws  -> String
    
    /**
     * Pauses playback
     */
    func pause() throws 
    
    /**
     * Resumes playback
     */
    func play() throws 
    
    /**
     * Plays a track by Spotify URI
     */
    func playUri(uri: String) throws 
    
    /**
     * Searches for tracks on Spotify with pagination support
     *
     * # Arguments
     * * `query` - The search query string
     * * `limit` - Maximum number of results to return (max 50)
     * * `offset` - The offset for pagination (0-based)
     */
    func search(query: String, limit: UInt32, offset: UInt32) throws  -> [PottyTrack]
    
    /**
     * Seeks to a position in the current track
     */
    func seek(positionMs: UInt32) throws 
    
    /**
     * Sets the delegate for player events
     */
    func setDelegate(delegate: PottyDelegate) 
    
    /**
     * Sets the playback volume (0-65535, where 65535 is 100%)
     */
    func setVolume(volume: UInt16) throws 
    
    /**
     * Stops playback
     */
    func stop() throws 
    
}

/**
 * Main client for the Potty Spotify bridge
 */
open class PottyClient:
    PottyClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_potty_bridge_fn_clone_pottyclient(self.pointer, $0) }
    }
    /**
     * Creates a new PottyClient instance
     */
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_potty_bridge_fn_constructor_pottyclient_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_potty_bridge_fn_free_pottyclient(pointer, $0) }
    }

    

    
    /**
     * Advanced search with filters and type selection
     *
     * # Arguments
     * * `query` - The base search query string
     * * `search_type` - Type of results to return (All, Track, Album, Artist)
     * * `artist_filter` - Optional artist name filter
     * * `album_filter` - Optional album name filter
     * * `track_filter` - Optional track name filter
     * * `limit` - Maximum number of results per type (max 50)
     * * `offset` - The offset for pagination (0-based)
     */
open func advancedSearch(query: String, searchType: PottySearchType, artistFilter: String?, albumFilter: String?, trackFilter: String?, limit: UInt32, offset: UInt32)throws  -> PottySearchResults {
    return try  FfiConverterTypePottySearchResults.lift(try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_advanced_search(self.uniffiClonePointer(),
        FfiConverterString.lower(query),
        FfiConverterTypePottySearchType.lower(searchType),
        FfiConverterOptionString.lower(artistFilter),
        FfiConverterOptionString.lower(albumFilter),
        FfiConverterOptionString.lower(trackFilter),
        FfiConverterUInt32.lower(limit),
        FfiConverterUInt32.lower(offset),$0
    )
})
}
    
    /**
     * Gets the user's liked/saved songs with pagination support
     *
     * # Arguments
     * * `offset` - The offset for pagination (0-based)
     * * `limit` - Maximum number of results to return (max 50)
     */
open func getLikedSongs(offset: UInt32, limit: UInt32)throws  -> [PottyTrack] {
    return try  FfiConverterSequenceTypePottyTrack.lift(try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_get_liked_songs(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(offset),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
    
    /**
     * Gets tracks from a specific playlist
     */
open func getPlaylistTracks(playlistId: String)throws  -> [PottyTrack] {
    return try  FfiConverterSequenceTypePottyTrack.lift(try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_get_playlist_tracks(self.uniffiClonePointer(),
        FfiConverterString.lower(playlistId),$0
    )
})
}
    
    /**
     * Gets the user's followed artists
     */
open func getUserFollowedArtists()throws  -> [PottyArtist] {
    return try  FfiConverterSequenceTypePottyArtist.lift(try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_get_user_followed_artists(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Gets the user's playlists
     */
open func getUserPlaylists()throws  -> [PottyPlaylist] {
    return try  FfiConverterSequenceTypePottyPlaylist.lift(try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_get_user_playlists(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Gets the user's saved albums with pagination support
     *
     * # Arguments
     * * `offset` - The offset for pagination (0-based)
     * * `limit` - Maximum number of results to return (max 50)
     */
open func getUserSavedAlbums(offset: UInt32, limit: UInt32)throws  -> [PottyAlbum] {
    return try  FfiConverterSequenceTypePottyAlbum.lift(try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_get_user_saved_albums(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(offset),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
    
    /**
     * Gets the current playback volume (0-65535, where 65535 is 100%)
     */
open func getVolume()throws  -> UInt16 {
    return try  FfiConverterUInt16.lift(try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_get_volume(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Authenticates with Spotify and initializes the session
     */
open func login()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_login(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Pauses playback
     */
open func pause()throws  {try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_pause(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Resumes playback
     */
open func play()throws  {try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_play(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Plays a track by Spotify URI
     */
open func playUri(uri: String)throws  {try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_play_uri(self.uniffiClonePointer(),
        FfiConverterString.lower(uri),$0
    )
}
}
    
    /**
     * Searches for tracks on Spotify with pagination support
     *
     * # Arguments
     * * `query` - The search query string
     * * `limit` - Maximum number of results to return (max 50)
     * * `offset` - The offset for pagination (0-based)
     */
open func search(query: String, limit: UInt32, offset: UInt32)throws  -> [PottyTrack] {
    return try  FfiConverterSequenceTypePottyTrack.lift(try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_search(self.uniffiClonePointer(),
        FfiConverterString.lower(query),
        FfiConverterUInt32.lower(limit),
        FfiConverterUInt32.lower(offset),$0
    )
})
}
    
    /**
     * Seeks to a position in the current track
     */
open func seek(positionMs: UInt32)throws  {try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_seek(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(positionMs),$0
    )
}
}
    
    /**
     * Sets the delegate for player events
     */
open func setDelegate(delegate: PottyDelegate) {try! rustCall() {
    uniffi_potty_bridge_fn_method_pottyclient_set_delegate(self.uniffiClonePointer(),
        FfiConverterCallbackInterfacePottyDelegate.lower(delegate),$0
    )
}
}
    
    /**
     * Sets the playback volume (0-65535, where 65535 is 100%)
     */
open func setVolume(volume: UInt16)throws  {try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_set_volume(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(volume),$0
    )
}
}
    
    /**
     * Stops playback
     */
open func stop()throws  {try rustCallWithError(FfiConverterTypePottyError.lift) {
    uniffi_potty_bridge_fn_method_pottyclient_stop(self.uniffiClonePointer(),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePottyClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PottyClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PottyClient {
        return PottyClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PottyClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PottyClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PottyClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottyClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> PottyClient {
    return try FfiConverterTypePottyClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottyClient_lower(_ value: PottyClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypePottyClient.lower(value)
}


/**
 * Represents a Spotify album with metadata
 */
public struct PottyAlbum {
    public var id: String
    public var name: String
    public var artist: String
    public var uri: String
    public var releaseDate: String
    public var totalTracks: UInt32
    public var imageUrl: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, artist: String, uri: String, releaseDate: String, totalTracks: UInt32, imageUrl: String) {
        self.id = id
        self.name = name
        self.artist = artist
        self.uri = uri
        self.releaseDate = releaseDate
        self.totalTracks = totalTracks
        self.imageUrl = imageUrl
    }
}



extension PottyAlbum: Equatable, Hashable {
    public static func ==(lhs: PottyAlbum, rhs: PottyAlbum) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.artist != rhs.artist {
            return false
        }
        if lhs.uri != rhs.uri {
            return false
        }
        if lhs.releaseDate != rhs.releaseDate {
            return false
        }
        if lhs.totalTracks != rhs.totalTracks {
            return false
        }
        if lhs.imageUrl != rhs.imageUrl {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(artist)
        hasher.combine(uri)
        hasher.combine(releaseDate)
        hasher.combine(totalTracks)
        hasher.combine(imageUrl)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePottyAlbum: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PottyAlbum {
        return
            try PottyAlbum(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                artist: FfiConverterString.read(from: &buf), 
                uri: FfiConverterString.read(from: &buf), 
                releaseDate: FfiConverterString.read(from: &buf), 
                totalTracks: FfiConverterUInt32.read(from: &buf), 
                imageUrl: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PottyAlbum, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.artist, into: &buf)
        FfiConverterString.write(value.uri, into: &buf)
        FfiConverterString.write(value.releaseDate, into: &buf)
        FfiConverterUInt32.write(value.totalTracks, into: &buf)
        FfiConverterString.write(value.imageUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottyAlbum_lift(_ buf: RustBuffer) throws -> PottyAlbum {
    return try FfiConverterTypePottyAlbum.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottyAlbum_lower(_ value: PottyAlbum) -> RustBuffer {
    return FfiConverterTypePottyAlbum.lower(value)
}


/**
 * Represents a Spotify artist with metadata
 */
public struct PottyArtist {
    public var id: String
    public var name: String
    public var uri: String
    public var genres: [String]
    public var imageUrl: String
    public var followers: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, uri: String, genres: [String], imageUrl: String, followers: UInt32) {
        self.id = id
        self.name = name
        self.uri = uri
        self.genres = genres
        self.imageUrl = imageUrl
        self.followers = followers
    }
}



extension PottyArtist: Equatable, Hashable {
    public static func ==(lhs: PottyArtist, rhs: PottyArtist) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.uri != rhs.uri {
            return false
        }
        if lhs.genres != rhs.genres {
            return false
        }
        if lhs.imageUrl != rhs.imageUrl {
            return false
        }
        if lhs.followers != rhs.followers {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(uri)
        hasher.combine(genres)
        hasher.combine(imageUrl)
        hasher.combine(followers)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePottyArtist: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PottyArtist {
        return
            try PottyArtist(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                uri: FfiConverterString.read(from: &buf), 
                genres: FfiConverterSequenceString.read(from: &buf), 
                imageUrl: FfiConverterString.read(from: &buf), 
                followers: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: PottyArtist, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.uri, into: &buf)
        FfiConverterSequenceString.write(value.genres, into: &buf)
        FfiConverterString.write(value.imageUrl, into: &buf)
        FfiConverterUInt32.write(value.followers, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottyArtist_lift(_ buf: RustBuffer) throws -> PottyArtist {
    return try FfiConverterTypePottyArtist.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottyArtist_lower(_ value: PottyArtist) -> RustBuffer {
    return FfiConverterTypePottyArtist.lower(value)
}


/**
 * Represents a Spotify playlist with metadata
 */
public struct PottyPlaylist {
    public var id: String
    public var name: String
    public var description: String
    public var uri: String
    public var trackCount: UInt32
    public var imageUrl: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, description: String, uri: String, trackCount: UInt32, imageUrl: String) {
        self.id = id
        self.name = name
        self.description = description
        self.uri = uri
        self.trackCount = trackCount
        self.imageUrl = imageUrl
    }
}



extension PottyPlaylist: Equatable, Hashable {
    public static func ==(lhs: PottyPlaylist, rhs: PottyPlaylist) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        if lhs.uri != rhs.uri {
            return false
        }
        if lhs.trackCount != rhs.trackCount {
            return false
        }
        if lhs.imageUrl != rhs.imageUrl {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(description)
        hasher.combine(uri)
        hasher.combine(trackCount)
        hasher.combine(imageUrl)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePottyPlaylist: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PottyPlaylist {
        return
            try PottyPlaylist(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                uri: FfiConverterString.read(from: &buf), 
                trackCount: FfiConverterUInt32.read(from: &buf), 
                imageUrl: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PottyPlaylist, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.uri, into: &buf)
        FfiConverterUInt32.write(value.trackCount, into: &buf)
        FfiConverterString.write(value.imageUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottyPlaylist_lift(_ buf: RustBuffer) throws -> PottyPlaylist {
    return try FfiConverterTypePottyPlaylist.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottyPlaylist_lower(_ value: PottyPlaylist) -> RustBuffer {
    return FfiConverterTypePottyPlaylist.lower(value)
}


/**
 * Unified search result
 */
public struct PottySearchResults {
    public var tracks: [PottyTrack]
    public var albums: [PottyAlbum]
    public var artists: [PottyArtist]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(tracks: [PottyTrack], albums: [PottyAlbum], artists: [PottyArtist]) {
        self.tracks = tracks
        self.albums = albums
        self.artists = artists
    }
}



extension PottySearchResults: Equatable, Hashable {
    public static func ==(lhs: PottySearchResults, rhs: PottySearchResults) -> Bool {
        if lhs.tracks != rhs.tracks {
            return false
        }
        if lhs.albums != rhs.albums {
            return false
        }
        if lhs.artists != rhs.artists {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(tracks)
        hasher.combine(albums)
        hasher.combine(artists)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePottySearchResults: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PottySearchResults {
        return
            try PottySearchResults(
                tracks: FfiConverterSequenceTypePottyTrack.read(from: &buf), 
                albums: FfiConverterSequenceTypePottyAlbum.read(from: &buf), 
                artists: FfiConverterSequenceTypePottyArtist.read(from: &buf)
        )
    }

    public static func write(_ value: PottySearchResults, into buf: inout [UInt8]) {
        FfiConverterSequenceTypePottyTrack.write(value.tracks, into: &buf)
        FfiConverterSequenceTypePottyAlbum.write(value.albums, into: &buf)
        FfiConverterSequenceTypePottyArtist.write(value.artists, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottySearchResults_lift(_ buf: RustBuffer) throws -> PottySearchResults {
    return try FfiConverterTypePottySearchResults.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottySearchResults_lower(_ value: PottySearchResults) -> RustBuffer {
    return FfiConverterTypePottySearchResults.lower(value)
}


/**
 * Represents a Spotify track with metadata
 */
public struct PottyTrack {
    public var id: String
    public var name: String
    public var artist: String
    public var album: String
    public var uri: String
    public var durationMs: UInt32
    public var imageUrl: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, artist: String, album: String, uri: String, durationMs: UInt32, imageUrl: String) {
        self.id = id
        self.name = name
        self.artist = artist
        self.album = album
        self.uri = uri
        self.durationMs = durationMs
        self.imageUrl = imageUrl
    }
}



extension PottyTrack: Equatable, Hashable {
    public static func ==(lhs: PottyTrack, rhs: PottyTrack) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.artist != rhs.artist {
            return false
        }
        if lhs.album != rhs.album {
            return false
        }
        if lhs.uri != rhs.uri {
            return false
        }
        if lhs.durationMs != rhs.durationMs {
            return false
        }
        if lhs.imageUrl != rhs.imageUrl {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(artist)
        hasher.combine(album)
        hasher.combine(uri)
        hasher.combine(durationMs)
        hasher.combine(imageUrl)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePottyTrack: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PottyTrack {
        return
            try PottyTrack(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                artist: FfiConverterString.read(from: &buf), 
                album: FfiConverterString.read(from: &buf), 
                uri: FfiConverterString.read(from: &buf), 
                durationMs: FfiConverterUInt32.read(from: &buf), 
                imageUrl: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PottyTrack, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.artist, into: &buf)
        FfiConverterString.write(value.album, into: &buf)
        FfiConverterString.write(value.uri, into: &buf)
        FfiConverterUInt32.write(value.durationMs, into: &buf)
        FfiConverterString.write(value.imageUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottyTrack_lift(_ buf: RustBuffer) throws -> PottyTrack {
    return try FfiConverterTypePottyTrack.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottyTrack_lower(_ value: PottyTrack) -> RustBuffer {
    return FfiConverterTypePottyTrack.lower(value)
}


/**
 * Core error type for the Potty bridge
 */
public enum PottyError {

    
    
    case Generic(String
    )
    case NotConnected
    case AuthenticationFailed(String
    )
    case PlaybackError(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePottyError: FfiConverterRustBuffer {
    typealias SwiftType = PottyError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PottyError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Generic(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .NotConnected
        case 3: return .AuthenticationFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .PlaybackError(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PottyError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Generic(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .NotConnected:
            writeInt(&buf, Int32(2))
        
        
        case let .AuthenticationFailed(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .PlaybackError(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension PottyError: Equatable, Hashable {}

extension PottyError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Player events that can be sent to the Swift UI
 */

public enum PottyPlayerEvent {
    
    case playing(trackId: String
    )
    case paused(trackId: String
    )
    case stopped(trackId: String
    )
    case endOfTrack(trackId: String
    )
    case volumeChanged(volume: UInt16
    )
    case unknown
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePottyPlayerEvent: FfiConverterRustBuffer {
    typealias SwiftType = PottyPlayerEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PottyPlayerEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .playing(trackId: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .paused(trackId: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .stopped(trackId: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .endOfTrack(trackId: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .volumeChanged(volume: try FfiConverterUInt16.read(from: &buf)
        )
        
        case 6: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PottyPlayerEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .playing(trackId):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(trackId, into: &buf)
            
        
        case let .paused(trackId):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(trackId, into: &buf)
            
        
        case let .stopped(trackId):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(trackId, into: &buf)
            
        
        case let .endOfTrack(trackId):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(trackId, into: &buf)
            
        
        case let .volumeChanged(volume):
            writeInt(&buf, Int32(5))
            FfiConverterUInt16.write(volume, into: &buf)
            
        
        case .unknown:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottyPlayerEvent_lift(_ buf: RustBuffer) throws -> PottyPlayerEvent {
    return try FfiConverterTypePottyPlayerEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottyPlayerEvent_lower(_ value: PottyPlayerEvent) -> RustBuffer {
    return FfiConverterTypePottyPlayerEvent.lower(value)
}



extension PottyPlayerEvent: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Search filter type
 */

public enum PottySearchType {
    
    case all
    case track
    case album
    case artist
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePottySearchType: FfiConverterRustBuffer {
    typealias SwiftType = PottySearchType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PottySearchType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .all
        
        case 2: return .track
        
        case 3: return .album
        
        case 4: return .artist
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PottySearchType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .all:
            writeInt(&buf, Int32(1))
        
        
        case .track:
            writeInt(&buf, Int32(2))
        
        
        case .album:
            writeInt(&buf, Int32(3))
        
        
        case .artist:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottySearchType_lift(_ buf: RustBuffer) throws -> PottySearchType {
    return try FfiConverterTypePottySearchType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePottySearchType_lower(_ value: PottySearchType) -> RustBuffer {
    return FfiConverterTypePottySearchType.lower(value)
}



extension PottySearchType: Equatable, Hashable {}






/**
 * Callback interface for player events
 */
public protocol PottyDelegate : AnyObject {
    
    func onPlayerEvent(event: PottyPlayerEvent) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfacePottyDelegate {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfacePottyDelegate = UniffiVTableCallbackInterfacePottyDelegate(
        onPlayerEvent: { (
            uniffiHandle: UInt64,
            event: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfacePottyDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onPlayerEvent(
                     event: try FfiConverterTypePottyPlayerEvent.lift(event)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfacePottyDelegate.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface PottyDelegate: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitPottyDelegate() {
    uniffi_potty_bridge_fn_init_callback_vtable_pottydelegate(&UniffiCallbackInterfacePottyDelegate.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfacePottyDelegate {
    fileprivate static var handleMap = UniffiHandleMap<PottyDelegate>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfacePottyDelegate : FfiConverter {
    typealias SwiftType = PottyDelegate
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePottyAlbum: FfiConverterRustBuffer {
    typealias SwiftType = [PottyAlbum]

    public static func write(_ value: [PottyAlbum], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePottyAlbum.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PottyAlbum] {
        let len: Int32 = try readInt(&buf)
        var seq = [PottyAlbum]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePottyAlbum.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePottyArtist: FfiConverterRustBuffer {
    typealias SwiftType = [PottyArtist]

    public static func write(_ value: [PottyArtist], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePottyArtist.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PottyArtist] {
        let len: Int32 = try readInt(&buf)
        var seq = [PottyArtist]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePottyArtist.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePottyPlaylist: FfiConverterRustBuffer {
    typealias SwiftType = [PottyPlaylist]

    public static func write(_ value: [PottyPlaylist], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePottyPlaylist.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PottyPlaylist] {
        let len: Int32 = try readInt(&buf)
        var seq = [PottyPlaylist]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePottyPlaylist.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePottyTrack: FfiConverterRustBuffer {
    typealias SwiftType = [PottyTrack]

    public static func write(_ value: [PottyTrack], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePottyTrack.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PottyTrack] {
        let len: Int32 = try readInt(&buf)
        var seq = [PottyTrack]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePottyTrack.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_potty_bridge_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_advanced_search() != 2335) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_get_liked_songs() != 35064) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_get_playlist_tracks() != 7230) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_get_user_followed_artists() != 31742) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_get_user_playlists() != 5371) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_get_user_saved_albums() != 29704) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_get_volume() != 29931) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_login() != 52505) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_pause() != 62593) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_play() != 16500) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_play_uri() != 58318) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_search() != 17927) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_seek() != 41630) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_set_delegate() != 12657) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_set_volume() != 3224) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottyclient_stop() != 39250) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_constructor_pottyclient_new() != 41625) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_potty_bridge_checksum_method_pottydelegate_on_player_event() != 49082) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitPottyDelegate()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all